spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: telegram-service
  config:
    import: "optional:configserver:http://localhost:8088"

bot:
  name: ${env.BOT_NAME}
  token: 832766512:AAEkYX4hYAM1HfGkWETQiuzYrBLlzCdfcuU
