server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: agenda-service
        uri: lb://agenda-service
        predicates:
          - Path=/agenda/**
        filters:
          - RewritePath=/agenda/(?<path>.*), /$\{path}
      - id: telegram-service
        uri: lb://telegram-service
        predicates:
        - Path=/telegram/**
        filters:
        - RewritePath=/telegram/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: employee
        url: /v3/api-docs/telegram

management:
  tracing:
    sampling:
      probability: 1.0