server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://87.248.168.158:8061/eureka/

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.flux.services.telegram

spring:
  activemq:
    topic: topic
    broker-url: tcp://87.248.168.158:61616
    user: admin
    password: admin
  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0