spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: agenda-service
  config:
    import: "optional:configserver:http://87.248.168.158:8088"